theme: jekyll-theme-cayman
show_downloads: true
github:
  zip_url: http://example.com/download.zip
  another_url: https://drive.google.com/file/d/10FdPLpW8pdXG3wx0f5vAdDYs-UVaLH0q/view?usp=sharing

  
 
